Backfill org ids
rust-lang/crates.io pull request #2796
Opened 2020-09-17 17:26 UTC by thiagoarrais

_This builds upon https://github.com/rust-lang/crates.io/pull/2725. I've created multiple PRs for us to focus review on specific issues. Feel free to close the [previous one](https://github.com/rust-lang/crates.io/pull/2725) if you folks prefer to review this as one big PR instead._

I've added a small program for backfilling the current database with the organization IDs for the existing teams.

It goes over all the teams in the database that don't have an org id (assuming that #2725 has been online for some time) and tries to query the [`/teams/:team_id`][team_legacy_ep] endpoint. Failing that, it parses the org name from the `login` field and queries [`/orgs/:org_name`][org_ep]. For the first part, I took advantage of the fact that I described in https://github.com/rust-lang/crates.io/issues/2619#issuecomment-689668261 about the `Link` header in GitHub's API.

The GitHub API calls are intended to run with crates.io's credentials. This assumes those will be available at `GH_CLIENT_ID` and `GH_CLIENT_SECRET`. There is no rate limiting on the client side. We have (at the time of writing) ~300 org ids to query. Since the GitHub limit is 5000 calls per hour per app and all requests are sequential, I've assumed that we wouldn't need to buffer calls on the client.

**Questions:**

1. Is `src/bin` the right place to add this? I don't think so, but couldn't find a better one.
2. Do you folks think we should do some buffering on the requests?
3. I couldn't find how to add dependencies for this binary only and included `parse_link_header` and `regex` to `Cargo.toml`. Is that OK?
4. We can detect future GitHub deprecation notices via this `Link` header. Should we integrate this into the main app (as a future issue/PR) and trigger some kind of automated warning?

[team_legacy_ep]: https://docs.github.com/en/rest/reference/teams#get-a-team-legacy
[org_ep]: https://docs.github.com/en/rest/reference/orgs#get-an-organization

2020-09-17 17:26 UTC, rust-highfive commented
r? @jtgeibel

(rust_highfive has picked a reviewer for you, use r? to override)

2020-10-05 16:47 UTC, thiagoarrais commented
@bors: +S-waiting-on-review -S-waiting-on-author

2020-10-05 17:07 UTC, jtgeibel requested changes
I have just one comment here which I forgot to submit. With this change I'll try it out on staging.

2020-10-06 14:48 UTC, thiagoarrais commented on src/bin/backfill-org-ids.rs
> +    conn.transaction::<_, diesel::result::Error, _>(|| {
Didn't actually consider that. I agree that individual updates are fine here. Will change that.

2020-10-16 11:49 UTC, jtgeibel commented
Thanks @thiagoarrais. We discussed this at our weekly team meeting and there was just one additional suggestion:

* To make sure we don't hit any rate limiting from GH, we should sleep for 1 second between requests.
  * We have ~250 teams to backfill in production, so this should still take <5 minutes to run.

Then, once the migration is complete, we'll want a PR that removes this binary. This is because we already have a lot of bins and that impacts our build time. Since this is a one-time migration we can drop the binary once the migration is complete. But for now, we just need to add the 1 second sleep and then I hope to have an opportunity to run the migration this weekend.

2020-10-19 17:14 UTC, thiagoarrais commented
Sorry. Couldn't get to this before the weekend.

I've added the sleep as requested. Just let me know when the migration is complete and I'll open the PR removing this bin.

2020-10-23 14:08 UTC, jtgeibel commented
Thanks @thiagoarrais! It turns out I didn't have time this past weekend anyway. I should have time to deploy and run it this weekend. I'll let you know once that is done.

@bors r+

2020-10-23 17:07 UTC, merged

2020-10-23 17:08 UTC, thiagoarrais commented
Nice! I'm planning on removing this new binary as part of #2810

2020-10-29 02:52 UTC, jtgeibel commented
Thanks @thiagoarrais! I just wanted to let you know that this is now deployed and I've run the backfill operation against production. It looks like the org id for 10 of the teams could not be found. For all 10, I've confirmed that I also cannot access the org via the GH website.

2020-10-29 17:50 UTC, thiagoarrais commented
Good to know, @jtgeibel! I have updated #2810 accordingly. It should be ready for review now.