Added Accessibility category
rust-lang/crates.io pull request #2998
Opened 2020-11-02 19:28 UTC by simonsan

I've added the `accessibility` category to cover crates that implement features for the convenience of disabled people.

I wanted to start a project that translates given colour codes to colours colorblind people can distinguish more easily, but I haven't found a category to fit it. What else belongs in this category could be crates that interoperate with peoples screenreaders, new screenreader implementations or other assistive technology.

2020-11-02 19:28 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @sgrif (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/crates.io/blob/master/docs/CONTRIBUTING.md) for more information.

2020-11-24 23:24 UTC, jtgeibel requested changes
Thanks for the PR @simonsan. I drew some inspiration from the [web accessibility docs](https://developer.mozilla.org/en-US/docs/Learn/Accessibility/What_is_accessibility#So_what_is_accessibility) and propose an alternate description.

2020-11-24 23:24 UTC, jtgeibel commented on src/boot/categories.toml
> +Crates that implement features for the convenience of disabled people. \
```suggestion
Tools for making your creations usable by as many people as possible. \
```

2020-11-25 12:57 UTC, simonsan commented
> 
> 
> Thanks for the PR @simonsan. I drew some inspiration from the [web accessibility docs](https://developer.mozilla.org/en-US/docs/Learn/Accessibility/What_is_accessibility#So_what_is_accessibility) and propose an alternate description.

Thanks for the input. ;-) Changed it.

2020-11-27 15:35 UTC, jtgeibel commented
Thanks @simonsan!

@bors r+

2020-11-27 15:40 UTC, merged